/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    colors: {
      background: "rgb(var(--background) / .2)",
      foreground: "rgb(var(--foreground) / .2)",
      muted: "rgb(var(--muted) / .2)",
      mutedForeground: "rgb(var(--muted-foreground) / .2)",
      popover: "rgb(var(--popover) / .2)",
      popoverForeground: "rgb(var(--popover-foreground) / .2)",
      border: "rgb(var(--border) / .2)",
      input: "rgb(var(--input) / .2)",
      card: "rgb(var(--card) / .2)",
      cardForeground: "rgb(var(--card-foreground) / .2)",
      primary: "rgb(var(--primary) / .2)",
      primaryForeground: "rgb(var(--primary-foreground) / .2)",
      secondary: "rgb(var(--secondary) / .2)",
      secondaryForeground: "rgb(var(--secondary-foreground) / .2)",
      accent: "rgb(var(--accent) / .2)",
      accentForeground: "rgb(var(--accent-foreground) / .2)",
      destructive: "rgb(var(--destructive) / .2)",
      destructiveForeground: "rgb(var(--destructive-foreground) / .2)",
      ring: "rgb(var(--ring) / .2)",
      radius: "rgb(var(--radius) / .2)",
    },
  },
  plugins: [
    // Set a default value on the `:root` element
    ({ addBase }) =>
      addBase({
        ":root": {
          "--background": "0 0% 100%",
          "--foreground": "222.2 47.4% 11.2%",
          "--muted": "210 40% 96.1%",
          "--muted-foreground": "215.4 16.3% 46.9%",
          "--popover": "0 0% 100%",
          "--popover-foreground": "222.2 47.4% 11.2%",
          "--border": "214.3 31.8% 91.4%",
          "--input": "214.3 31.8% 91.4%",
          "--card": "0 0% 100%",
          "--card-foreground": "222.2 47.4% 11.2%",
          "--primary": "222.2 47.4% 11.2%",
          "--primary-foreground": "210 40% 98%",
          "--secondary": "210 40% 96.1%",
          "--secondary-foreground": "222.2 47.4% 11.2%",
          "--accent": "210 40% 96.1%",
          "--accent-foreground": "222.2 47.4% 11.2%",
          "--destructive": "0 100% 50%",
          "--destructive-foreground": "210 40% 98%",
          "--ring": "215 20.2% 65.1%",
          "--radius": "0.5rem",
        },
      }),
  ],
};
